name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  secret-scan:
    uses: wcmchenry3-stack/.github/.github/workflows/called-secret-scan.yml@main
    secrets: inherit

  lint-frontend:
    uses: wcmchenry3-stack/.github/.github/workflows/called-lint-frontend.yml@main
    with:
      run-a11y: true
    secrets: inherit

  test-frontend:
    uses: wcmchenry3-stack/.github/.github/workflows/called-test-frontend.yml@main
    with:
      coverage-threshold: 80
    secrets: inherit

  build-frontend:
    uses: wcmchenry3-stack/.github/.github/workflows/called-build-frontend.yml@main
    secrets: inherit

  cve-frontend:
    uses: wcmchenry3-stack/.github/.github/workflows/called-cve-frontend.yml@main
    secrets: inherit
